name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test_ubuntu_18:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: bash test/run.sh
      env:
        STACK: scalingo-18 
  test_ubuntu_20:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: bash test/run.sh
      env:
        STACK: scalingo-20 
